# Global settings
device: "cuda"
seed: 42

# Video processing
video:
  frame_sample_rate: 1
  model_name: "dima806/deepfake_vs_real_image_detection"
  batch_size: 8
  face_detection: false

# Audio processing
audio:
  model_name: "facebook/wav2vec2-base-960h"
  sample_rate: 16000
  use_asr: false

# Text processing
text:
  model_name: "roberta-base-openai-detector"
  max_length: 512

# FAISS retrieval
#retrieval:
#  articles_path: "data/articles.json"
#  index_path: "data/faiss_index.bin"
 # embedder_model: "all-MiniLM-L6-v2"
  #top_k: 5

# Paths
temp_dir: "data/processed"

retrieval:
  articles_path: "data/articles.json"
  index_path: "data/faiss/index.faiss"
  embedder_model: "sentence-transformers/all-MiniLM-L6-v2"
  top_k: 5
